[package]
name = "area_of_triangle"
version = "0.1.0"
authors = ["GMitchell98 <g.mitchell9@rgu.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
